### ISSUE TITLE
data is not available

### ISSUE THREAD

**Issue by zhangzeng9730** [igabr/Metis_Projects_Chicago_2017#2]
Hi,

Thank you so much for your great work done! However, I just figured out that the data provided there is not available anymore. Could you please update it?

Best,
Zhang Zeng

**Comment by igabr** [comment]
Hey Zhang,

It seems that the original providor of the data is no longer sharing that data source.

I cannot share the data source since I do not procure it myself. I had to obtain explicit permission from the author to use the data. Furthermore, the data in question is quite old now.

I would recommend https://blockchain.info/ as a data source.

Cheers!
